<?php

namespace App\Services\Modules\SampleData;

class FinanceSampleData
{
    /**
     * Default realistic mock Finance records for V1.
     */
    public static function get(int $accountId, ?int $userId = null): array
    {
        return self::getDefaultFinanceRecords($accountId, $userId);
    }

    public static function getDefaultFinanceRecords(int $accountId, ?int $userId = null): array
    {
        return [
            // RECEIVABLES
            [
                'id' => 1,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'receivable',
                'reference_no' => 'INV-2026-0182',
                'title' => 'Client Advisory & Consulting Invoice',
                'category' => 'Receivable',
                'amount' => 125000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱125,000.00',
                'record_date' => '2026-08-18',
                'formatted_record_date' => 'Aug 18, 2026',
                'due_date' => '2026-09-30',
                'formatted_due_date' => 'Sep 30, 2026',
                'status' => 'Unpaid',
                'status_badge_class' => 'unpaid',
                'description' => 'Professional management advisory and SEC compliance filing retainer for Q3.',
                'metadata' => [
                    'client_name' => 'Apex Holdings Philippines Inc.',
                    'invoice_no' => 'INV-2026-0182',
                    'payment_terms' => 'Net 30',
                    'tax_withheld' => '₱2,500.00 (2% CWT)',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Invoice_INV-2026-0182.pdf',
            ],
            [
                'id' => 2,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'receivable',
                'reference_no' => 'INV-2026-0183',
                'title' => 'Corporate Secretarial Services Q3 Retainer',
                'category' => 'Receivable',
                'amount' => 65000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱65,000.00',
                'record_date' => '2026-08-15',
                'formatted_record_date' => 'Aug 15, 2026',
                'due_date' => '2026-09-20',
                'formatted_due_date' => 'Sep 20, 2026',
                'status' => 'Unpaid',
                'status_badge_class' => 'unpaid',
                'description' => 'Board meeting documentation, minute book maintenance, and corporate governance filings.',
                'metadata' => [
                    'client_name' => 'Pacific Star Ventures Corp.',
                    'invoice_no' => 'INV-2026-0183',
                    'payment_terms' => 'Net 15',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Invoice_INV-2026-0183.pdf',
            ],
            [
                'id' => 3,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'receivable',
                'reference_no' => 'INV-2026-0184',
                'title' => 'Annual Regulatory Compliance Review Fee',
                'category' => 'Receivable',
                'amount' => 35000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱35,000.00',
                'record_date' => '2026-08-10',
                'formatted_record_date' => 'Aug 10, 2026',
                'due_date' => '2026-09-10',
                'formatted_due_date' => 'Sep 10, 2026',
                'status' => 'Paid',
                'status_badge_class' => 'approved',
                'description' => 'Statutory audit prep assistance and internal accounting compliance verification.',
                'metadata' => [
                    'client_name' => 'Metrostar Trading & Logistics Inc.',
                    'invoice_no' => 'INV-2026-0184',
                    'settlement_ref' => 'WIRE-MBTC-88910',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Invoice_INV-2026-0184.pdf',
            ],

            // PAYABLES
            [
                'id' => 4,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'payable',
                'reference_no' => 'PAY-2026-0061',
                'title' => 'AWS Cloud Infrastructure Hosting Bill',
                'category' => 'Payable',
                'amount' => 48500.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱48,500.00',
                'record_date' => '2026-08-17',
                'formatted_record_date' => 'Aug 17, 2026',
                'due_date' => '2026-09-25',
                'formatted_due_date' => 'Sep 25, 2026',
                'status' => 'Approved',
                'status_badge_class' => 'approved',
                'description' => 'Dedicated cloud portal servers, automated database backups, and secure SSL acceleration.',
                'metadata' => [
                    'vendor_name' => 'Amazon Web Services, Inc.',
                    'bill_no' => 'AWS-PH-2026-8812',
                    'payment_method' => 'Corporate Credit Card',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Supplier_Bill_PAY-2026-0061.pdf',
            ],
            [
                'id' => 5,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'payable',
                'reference_no' => 'PAY-2026-0062',
                'title' => 'External Legal Counsel Retainer Fee',
                'category' => 'Payable',
                'amount' => 25000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱25,000.00',
                'record_date' => '2026-08-14',
                'formatted_record_date' => 'Aug 14, 2026',
                'due_date' => '2026-10-05',
                'formatted_due_date' => 'Oct 05, 2026',
                'status' => 'Approved',
                'status_badge_class' => 'approved',
                'description' => 'General legal advisory, contract vetting, and commercial dispute monitoring.',
                'metadata' => [
                    'vendor_name' => 'Romulo Law Offices',
                    'bill_no' => 'BILL-ROM-2026-041',
                    'payment_method' => 'Bank Transfer',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 6,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'payable',
                'reference_no' => 'PAY-2026-0063',
                'title' => 'Office Space Lease & Facilities Maintenance',
                'category' => 'Payable',
                'amount' => 10500.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱10,500.00',
                'record_date' => '2026-08-12',
                'formatted_record_date' => 'Aug 12, 2026',
                'due_date' => '2026-09-28',
                'formatted_due_date' => 'Sep 28, 2026',
                'status' => 'Pending',
                'status_badge_class' => 'pending',
                'description' => 'Building association dues, communal air-conditioning, and 24/7 security maintenance.',
                'metadata' => [
                    'vendor_name' => 'Pacific Star Building Property Admin',
                    'bill_no' => 'SOA-PSB-2026-08',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // EXPENSES
            [
                'id' => 7,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'expense',
                'reference_no' => 'EXP-2026-0145',
                'title' => 'Enterprise Productivity Software Suite',
                'category' => 'Expense',
                'amount' => 54200.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱54,200.00',
                'record_date' => '2026-08-16',
                'formatted_record_date' => 'Aug 16, 2026',
                'due_date' => null,
                'status' => 'Recorded',
                'status_badge_class' => 'recorded',
                'description' => 'Annual enterprise licenses for Slack Workspace, Google Workspace Business Plus, and Zoom Pro.',
                'metadata' => [
                    'payee' => 'Google & Slack Enterprise',
                    'expense_type' => 'Software & Subscriptions',
                    'payment_method' => 'Corporate Card',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Receipt_EXP-2026-0145.pdf',
            ],
            [
                'id' => 8,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'expense',
                'reference_no' => 'EXP-2026-0146',
                'title' => 'Strategic Management Planning Session',
                'category' => 'Expense',
                'amount' => 38600.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱38,600.00',
                'record_date' => '2026-08-11',
                'formatted_record_date' => 'Aug 11, 2026',
                'due_date' => null,
                'status' => 'Recorded',
                'status_badge_class' => 'recorded',
                'description' => 'Leadership summit conference hall booking, presentation materials, and executive team catering.',
                'metadata' => [
                    'payee' => 'Shangri-La The Fort Manila',
                    'expense_type' => 'Business Meetings',
                    'payment_method' => 'Bank Transfer',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 9,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'expense',
                'reference_no' => 'EXP-2026-0147',
                'title' => 'High-Speed Dedicated Fiber Internet',
                'category' => 'Expense',
                'amount' => 25200.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱25,200.00',
                'record_date' => '2026-08-08',
                'formatted_record_date' => 'Aug 08, 2026',
                'due_date' => null,
                'status' => 'Recorded',
                'status_badge_class' => 'recorded',
                'description' => 'Office redundant dedicated internet leased line and static IP block subscription.',
                'metadata' => [
                    'payee' => 'PLDT Enterprise',
                    'expense_type' => 'Utilities',
                    'payment_method' => 'Direct Debit',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // TRANSACTIONS
            [
                'id' => 10,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'transaction',
                'reference_no' => 'TRX-2026-0034',
                'title' => 'Inbound Customer Wire Settlement',
                'category' => 'Transaction',
                'amount' => 180000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱180,000.00',
                'record_date' => '2026-08-18',
                'formatted_record_date' => 'Aug 18, 2026',
                'due_date' => null,
                'status' => 'Settled',
                'status_badge_class' => 'approved',
                'description' => 'Full settlement of client billing received through Metrobank PESONet corporate gateway.',
                'metadata' => [
                    'transaction_type' => 'Inbound Payment',
                    'bank_account' => 'Metrobank Corporate #9921',
                    'trace_no' => 'PNT-2026-0818-4421',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Bank_Confirmation_TRX-2026-0034.pdf',
            ],
            [
                'id' => 11,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'transaction',
                'reference_no' => 'TRX-2026-0035',
                'title' => 'Semi-Monthly Payroll Automated Disbursement',
                'category' => 'Transaction',
                'amount' => 145000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱145,000.00',
                'record_date' => '2026-08-15',
                'formatted_record_date' => 'Aug 15, 2026',
                'due_date' => null,
                'status' => 'Settled',
                'status_badge_class' => 'approved',
                'description' => 'Disbursement of employee salaries, mandatory tax withholdings, and government statutory dues.',
                'metadata' => [
                    'transaction_type' => 'Payroll Outflow',
                    'bank_account' => 'BDO Corporate Cash #1044',
                    'batch_id' => 'PAYROLL-2026-08A',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 12,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'transaction',
                'reference_no' => 'TRX-2026-0036',
                'title' => 'Vendor Manager Check Clearing',
                'category' => 'Transaction',
                'amount' => 48500.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱48,500.00',
                'record_date' => '2026-08-13',
                'formatted_record_date' => 'Aug 13, 2026',
                'due_date' => null,
                'status' => 'Settled',
                'status_badge_class' => 'approved',
                'description' => 'Manager check encashment cleared for cloud infrastructure maintenance and security audit.',
                'metadata' => [
                    'transaction_type' => 'Check Settlement',
                    'bank_account' => 'UnionBank Business #7119',
                    'check_no' => 'MC-0044921',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // REQUESTS
            [
                'id' => 13,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'request',
                'reference_no' => 'REQ-2026-0012',
                'title' => 'IT Infrastructure Hardware Upgrade Request',
                'category' => 'Request',
                'amount' => 75000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱75,000.00',
                'record_date' => '2026-08-17',
                'formatted_record_date' => 'Aug 17, 2026',
                'due_date' => '2026-09-01',
                'formatted_due_date' => 'Sep 01, 2026',
                'status' => 'Pending',
                'status_badge_class' => 'pending',
                'description' => 'Requisition for 3 development workstations and encrypted backup external storage drives.',
                'metadata' => [
                    'department' => 'Technology & Systems',
                    'requester' => 'Lead Systems Engineer',
                    'priority' => 'High',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Requisition_REQ-2026-0012.pdf',
            ],
            [
                'id' => 14,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'request',
                'reference_no' => 'REQ-2026-0013',
                'title' => 'Quarterly Statutory Audit Preparation Advance',
                'category' => 'Request',
                'amount' => 30000.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱30,000.00',
                'record_date' => '2026-08-09',
                'formatted_record_date' => 'Aug 09, 2026',
                'due_date' => '2026-08-25',
                'formatted_due_date' => 'Aug 25, 2026',
                'status' => 'Approved',
                'status_badge_class' => 'approved',
                'description' => 'Fund release for external tax auditor working papers, printing, and regulatory stamping fees.',
                'metadata' => [
                    'department' => 'Finance & Accounting',
                    'requester' => 'Senior Accountant',
                    'priority' => 'Standard',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // FINANCE RECORDS (GENERAL)
            [
                'id' => 15,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'finance_record',
                'reference_no' => 'FIN-2026-0096',
                'title' => 'FY2025 Audited Financial Statements & Tax Notes',
                'category' => 'Financial Record',
                'amount' => 0.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱0.00',
                'record_date' => '2026-08-15',
                'formatted_record_date' => 'Aug 15, 2026',
                'due_date' => null,
                'status' => 'Recorded',
                'status_badge_class' => 'recorded',
                'description' => 'Complete audited balance sheet, income statement, cash flow schedule, and independent auditor opinion report.',
                'metadata' => [
                    'record_category' => 'Audited Financial Statements',
                    'custodian' => 'Finance & Compliance Department',
                    'auditor' => 'Sycip Gorres Velayo & Co. (SGV)',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Audited_FS_FY2025_Final.pdf',
            ],
            [
                'id' => 16,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'finance_record',
                'reference_no' => 'FIN-2026-0097',
                'title' => 'Monthly Bank Reconciliation Summary - BDO',
                'category' => 'Financial Record',
                'amount' => 0.00,
                'currency' => 'PHP',
                'formatted_amount' => '₱0.00',
                'record_date' => '2026-08-14',
                'formatted_record_date' => 'Aug 14, 2026',
                'due_date' => null,
                'status' => 'Approved',
                'status_badge_class' => 'approved',
                'description' => 'Monthly bank ledger to general ledger reconciliation, outstanding check schedule, and interest adjustments.',
                'metadata' => [
                    'record_category' => 'Bank Reconciliation',
                    'account_name' => 'BDO Corporate Checking #1044',
                    'reviewer' => 'Finance Manager',
                ],
                'attachment_path' => null,
                'attachment_name' => 'BDO_Recon_Aug2026.pdf',
            ],
        ];
    }
}
