<?php

namespace App\Services\Modules\SampleData;

class GovernanceSampleData
{
    /**
     * Default mock governance records for V1.
     */
    public static function get(int $accountId, ?int $userId = null): array
    {
        return self::getDefaultGovernanceRecords($accountId, $userId);
    }

    public static function getDefaultGovernanceRecords(int $accountId, ?int $userId = null): array
    {
        return [
            [
                'id' => 1,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'resolution',
                'reference_no' => 'BR-2026-041',
                'title' => 'Board Resolution',
                'category' => 'Governance',
                'record_date' => '2026-08-17',
                'formatted_record_date' => 'Aug 17, 2026',
                'status' => 'Approved',
                'status_badge_class' => 'approved',
                'description' => 'Authorized designated officers to execute corporate financing agreements and banking arrangements.',
                'metadata' => [
                    'resolution_type' => 'Board Resolution',
                    'signatory' => 'Corporate Secretary',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Board_Resolution_BR-2026-041.pdf',
            ],
            [
                'id' => 2,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'corporate_record',
                'reference_no' => 'SC-2026-018',
                'title' => "Secretary's Certificate",
                'category' => 'Corporate record',
                'record_date' => '2026-08-15',
                'formatted_record_date' => 'Aug 15, 2026',
                'status' => 'Final',
                'status_badge_class' => 'final',
                'description' => 'Certified extract of the minutes of the regular meeting of the Board of Directors.',
                'metadata' => [
                    'record_category' => 'Certificate',
                    'custodian' => 'Office of the Corporate Secretary',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Secretary_Certificate_SC-2026-018.pdf',
            ],
            [
                'id' => 3,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'meeting',
                'reference_no' => 'MIN-2026-009',
                'title' => 'Special Board Meeting Minutes',
                'category' => 'Meeting record',
                'record_date' => '2026-08-10',
                'formatted_record_date' => 'Aug 10, 2026',
                'status' => 'For Review',
                'status_badge_class' => 'review',
                'description' => 'Deliberation of Q3 business expansion roadmap, capital expenditure approvals, and corporate restructuring.',
                'metadata' => [
                    'meeting_type' => 'Special Board Meeting',
                    'location' => 'Executive Boardroom / Hybrid Zoom',
                    'presiding_officer' => 'Chairman & CEO',
                    'quorum' => '5 of 5 Present',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 4,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'ownership',
                'reference_no' => 'OWN-2026-001',
                'title' => 'Mendoza Capital Holdings, Inc.',
                'category' => 'Common Shares',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Primary institutional shareholding representing 510,000 common voting shares.',
                'metadata' => [
                    'shareholder_type' => 'Corporate / Institutional',
                    'share_count' => '510,000',
                    'ownership_percentage' => '51.00%',
                    'certificate_no' => 'CERT-0001',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 5,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'director_officer',
                'reference_no' => 'DO-2026-001',
                'title' => 'Atty. Carlos Mendoza',
                'category' => 'President & Director',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Principal corporate representative and authorized signatory for SEC and regulatory filings.',
                'metadata' => [
                    'nationality' => 'Filipino',
                    'position' => 'President & Director',
                    'term_end' => '2027-01-15',
                    'tin' => '123-456-789-000',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 6,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'entity_profile',
                'reference_no' => 'EP-2026-001',
                'title' => 'Acme Global Ventures Inc.',
                'category' => 'Stock Corporation',
                'record_date' => '2025-01-10',
                'formatted_record_date' => 'Jan 10, 2025',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Primary operating corporation registered with Securities and Exchange Commission (SEC).',
                'metadata' => [
                    'sec_registration_no' => 'CS202500123',
                    'tin' => '009-876-543-000',
                    'principal_address' => 'Floor 28, Pacific Star Bldg, Makati City',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 7,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'director_officer',
                'reference_no' => 'DO-2026-002',
                'title' => 'Maria Lourdes Santos',
                'category' => 'Corporate Secretary',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Appointed Corporate Secretary and Compliance Officer.',
                'metadata' => [
                    'nationality' => 'Filipino',
                    'position' => 'Corporate Secretary',
                    'term_end' => '2027-01-15',
                    'tin' => '234-567-890-000',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 8,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'director_officer',
                'reference_no' => 'DO-2026-003',
                'title' => 'Ramon F. Fernandez',
                'category' => 'Treasurer',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Chief Financial Officer and Corporate Treasurer.',
                'metadata' => [
                    'nationality' => 'Filipino',
                    'position' => 'Treasurer & CFO',
                    'term_end' => '2027-01-15',
                    'tin' => '345-678-901-000',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 9,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'director_officer',
                'reference_no' => 'DO-2026-004',
                'title' => 'Engr. Victoria Ramos',
                'category' => 'Executive Vice President',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Executive Director in charge of Strategic Operations.',
                'metadata' => [
                    'nationality' => 'Filipino',
                    'position' => 'Executive Vice President',
                    'term_end' => '2027-01-15',
                    'tin' => '456-789-012-000',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 10,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'director_officer',
                'reference_no' => 'DO-2026-005',
                'title' => 'Jaime K. Castillo',
                'category' => 'Independent Director',
                'record_date' => '2026-01-15',
                'formatted_record_date' => 'Jan 15, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Independent Director, Audit and Risk Oversight Committee Chairman.',
                'metadata' => [
                    'nationality' => 'Filipino',
                    'position' => 'Independent Director',
                    'term_end' => '2027-01-15',
                    'tin' => '567-890-123-000',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 11,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'resolution',
                'reference_no' => 'BR-2026-042',
                'title' => 'Stock Option Grant Resolution',
                'category' => 'Board Resolution',
                'record_date' => '2026-08-20',
                'formatted_record_date' => 'Aug 20, 2026',
                'status' => 'Pending Signature',
                'status_badge_class' => 'review',
                'description' => 'Board resolution granting employee stock options awaiting Chairman signature.',
                'metadata' => [
                    'resolution_type' => 'Board Resolution',
                    'resolution_no' => 'BR-2026-042',
                    'signatory' => 'Corporate Secretary',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 12,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'corporate_record',
                'reference_no' => 'SC-2026-019',
                'title' => 'Articles of Incorporation Amendment',
                'category' => 'Corporate record',
                'record_date' => '2026-08-22',
                'formatted_record_date' => 'Aug 22, 2026',
                'status' => 'For Review',
                'status_badge_class' => 'review',
                'description' => 'Draft amended articles for secondary business licensing.',
                'metadata' => [
                    'filing_agency' => 'Securities and Exchange Commission',
                    'custodian' => 'Legal Department',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 13,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'meeting',
                'reference_no' => 'MIN-2026-010',
                'title' => 'Q3 Regular Stockholders Assembly',
                'category' => 'Meeting record',
                'record_date' => '2026-09-30',
                'formatted_record_date' => 'Sep 30, 2026',
                'status' => 'Scheduled',
                'status_badge_class' => 'scheduled',
                'description' => 'Upcoming hybrid stockholders meeting scheduled for Q3.',
                'metadata' => [
                    'location' => 'Grand Ballroom & Zoom Hybrid',
                    'presiding_officer' => 'Chairman Carlos Mendoza',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 14,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'entity_profile',
                'reference_no' => 'EP-2026-002',
                'title' => 'Apex Pacific Holdings Corp.',
                'category' => 'Domestic Holding Corporation',
                'record_date' => '2025-06-18',
                'formatted_record_date' => 'Jun 18, 2025',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Subsidiary investment holding corporation.',
                'metadata' => [
                    'sec_registration_no' => 'CS202509876',
                    'tin' => '009-123-456-000',
                    'principal_address' => 'Makati City, Philippines',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 15,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'ownership',
                'reference_no' => 'OWN-2026-002',
                'title' => 'Pacific Star Equity Partners',
                'category' => 'Common Shares',
                'record_date' => '2026-01-20',
                'formatted_record_date' => 'Jan 20, 2026',
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Subscribed 250,000 common shares representing 25.00% equity.',
                'metadata' => [
                    'shareholder_type' => 'Corporate / Institutional',
                    'share_count' => '250,000',
                    'ownership_percentage' => '25.00%',
                    'certificate_no' => 'CERT-0002',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
        ];
    }
}
