<?php

namespace App\Services\Modules\SampleData;

class HumanCapitalSampleData
{
    /**
     * Default recent activities for Human Capital.
     */
    public static function getActivities(int $accountId): array
    {
        return self::getDefaultHumanCapitalActivities($accountId);
    }

    public static function getDefaultHumanCapitalActivities(int $accountId): array
    {
        return [
            [
                'title' => 'Annual Medical & Health Clearance uploaded for Maria Santos',
                'type' => 'HR Document',
                'time' => '2 hours ago',
                'created_at' => date('Y-m-d H:i:s', strtotime('-2 hours')),
            ],
            [
                'title' => 'Vacation Leave request approved for Roberto Jose Dizon (Sep 7–11)',
                'type' => 'Leave',
                'time' => 'Yesterday',
                'created_at' => date('Y-m-d H:i:s', strtotime('-1 day')),
            ],
            [
                'title' => 'Daily attendance logged for Operations & Engineering teams',
                'type' => 'Attendance',
                'time' => 'Today 09:15 AM',
                'created_at' => date('Y-m-d 09:15:00'),
            ],
            [
                'title' => 'Work arrangement updated to Remote for Mark Gabriel Cruz',
                'type' => 'Employee',
                'time' => '3 days ago',
                'created_at' => date('Y-m-d H:i:s', strtotime('-3 days')),
            ],
            [
                'title' => 'Regularization performance review completed for Beatrice Anne Tan',
                'type' => 'HR Milestone',
                'time' => '1 week ago',
                'created_at' => date('Y-m-d H:i:s', strtotime('-7 days')),
            ],
        ];
    }

    /**
     * Default realistic mock records for Human Capital (Employees, HR Docs, Attendance, Leaves).
     */
    public static function getRecords(int $accountId, ?int $userId = null): array
    {
        return self::getDefaultHumanCapitalRecords($accountId, $userId);
    }

    public static function getDefaultHumanCapitalRecords(int $accountId, ?int $userId = null): array
    {
        return [
            // EMPLOYEES
            [
                'id' => 1,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-001',
                'title' => 'Maria Santos',
                'category' => 'Executive & Operations',
                'record_date' => '2022-01-15',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Oversees day-to-day organizational operations and client delivery standards.',
                'metadata' => [
                    'employee_id' => 'EMP-001',
                    'employee_name' => 'Maria Santos',
                    'department' => 'Executive & Operations',
                    'position' => 'Head of Operations',
                    'employment_type' => 'Regular',
                    'work_arrangement' => 'On-site',
                    'date_hired' => '2022-01-15',
                    'reporting_manager' => 'Chief Executive Officer',
                    'employment_status' => 'Active',
                    'notes' => 'Executive management key signatory and senior operating leader.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Employment_Contract_EMP-001.pdf',
            ],
            [
                'id' => 2,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-002',
                'title' => 'Atty. Juan Carlos Reyes',
                'category' => 'Legal & Compliance',
                'record_date' => '2023-03-01',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Leads regulatory compliance, statutory filings, and commercial contract negotiations.',
                'metadata' => [
                    'employee_id' => 'EMP-002',
                    'employee_name' => 'Atty. Juan Carlos Reyes',
                    'department' => 'Legal & Compliance',
                    'position' => 'Senior Corporate Counsel',
                    'employment_type' => 'Regular',
                    'work_arrangement' => 'Hybrid',
                    'date_hired' => '2023-03-01',
                    'reporting_manager' => 'Head of Operations',
                    'employment_status' => 'Active',
                    'notes' => 'Bar-admitted attorney managing Philippine and cross-border commercial transactions.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Appointment_Letter_EMP-002.pdf',
            ],
            [
                'id' => 3,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-003',
                'title' => 'Ana Patricia Lim',
                'category' => 'Finance & Accounting',
                'record_date' => '2023-06-12',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Certified Public Accountant managing tax compliance, monthly closings, and financial auditing.',
                'metadata' => [
                    'employee_id' => 'EMP-003',
                    'employee_name' => 'Ana Patricia Lim',
                    'department' => 'Finance & Accounting',
                    'position' => 'Senior Accountant',
                    'employment_type' => 'Regular',
                    'work_arrangement' => 'Hybrid',
                    'date_hired' => '2023-06-12',
                    'reporting_manager' => 'Corporate Treasurer',
                    'employment_status' => 'Active',
                    'notes' => 'Supervises accounts payable, tax returns, and external auditor liaison.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'CPA_Credentials_EMP-003.pdf',
            ],
            [
                'id' => 4,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-004',
                'title' => 'Mark Gabriel Cruz',
                'category' => 'Technology & Systems',
                'record_date' => '2023-09-05',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Responsible for core server architecture, automated backups, and information security.',
                'metadata' => [
                    'employee_id' => 'EMP-004',
                    'employee_name' => 'Mark Gabriel Cruz',
                    'department' => 'Technology & Systems',
                    'position' => 'Systems Infrastructure Engineer',
                    'employment_type' => 'Regular',
                    'work_arrangement' => 'Remote',
                    'date_hired' => '2023-09-05',
                    'reporting_manager' => 'Chief Technology Officer',
                    'employment_status' => 'Active',
                    'notes' => 'Lead administrator for cloud servers and enterprise portal endpoints.',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 5,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-005',
                'title' => 'Beatrice Anne Tan',
                'category' => 'Human Resources',
                'record_date' => '2024-02-10',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Manages talent acquisition, onboarding workflows, employee engagement, and statutory benefits.',
                'metadata' => [
                    'employee_id' => 'EMP-005',
                    'employee_name' => 'Beatrice Anne Tan',
                    'department' => 'Human Resources',
                    'position' => 'HR Business Partner',
                    'employment_type' => 'Regular',
                    'work_arrangement' => 'On-site',
                    'date_hired' => '2024-02-10',
                    'reporting_manager' => 'Head of Operations',
                    'employment_status' => 'Active',
                    'notes' => 'Primary point of contact for DOLE, SSS, PhilHealth, and Pag-IBIG matters.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'HRBP_Job_Description_EMP-005.pdf',
            ],
            [
                'id' => 6,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'employee',
                'reference_no' => 'EMP-006',
                'title' => 'Roberto Jose Dizon',
                'category' => 'Operations & Logistics',
                'record_date' => '2024-05-02',
                'end_date' => null,
                'status' => 'On Leave',
                'status_badge_class' => 'review',
                'description' => 'Handles warehouse logistics, physical parcel dispatch, and local transmittal coordination.',
                'metadata' => [
                    'employee_id' => 'EMP-006',
                    'employee_name' => 'Roberto Jose Dizon',
                    'department' => 'Operations & Logistics',
                    'position' => 'Logistics Specialist',
                    'employment_type' => 'Contractual',
                    'work_arrangement' => 'On-site',
                    'date_hired' => '2024-05-02',
                    'reporting_manager' => 'Head of Operations',
                    'employment_status' => 'On Leave',
                    'notes' => 'Currently on approved annual leave from Sep 07 to Sep 11, 2026.',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // HR RECORDS / DOCUMENTS
            [
                'id' => 7,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'hr_document',
                'reference_no' => 'HRD-2026-0088',
                'title' => 'Executive Employment Agreement - Juan Carlos Reyes',
                'category' => 'Employment Contract',
                'record_date' => '2026-08-10',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Executed regular employment contract specifying legal advisory scope and confidentiality covenants.',
                'metadata' => [
                    'employee_name' => 'Atty. Juan Carlos Reyes',
                    'document_type' => 'Employment Contract',
                    'title' => 'Executive Employment Agreement - Juan Carlos Reyes',
                    'status' => 'Active',
                    'description' => 'Executed regular employment contract specifying legal advisory scope and confidentiality covenants.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Employment_Agreement_Signed.pdf',
            ],
            [
                'id' => 8,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'hr_document',
                'reference_no' => 'HRD-2026-0087',
                'title' => 'Annual Medical & Health Examination Clearance',
                'category' => 'Medical Clearance',
                'record_date' => '2026-08-05',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Annual comprehensive physical and occupational health fitness certification from partner diagnostic clinic.',
                'metadata' => [
                    'employee_name' => 'Maria Santos',
                    'document_type' => 'Medical Clearance',
                    'title' => 'Annual Medical & Health Examination Clearance',
                    'status' => 'Active',
                    'description' => 'Annual comprehensive physical and occupational health fitness certification from partner diagnostic clinic.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Annual_Medical_FitToWork_2026.pdf',
            ],
            [
                'id' => 9,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'hr_document',
                'reference_no' => 'HRD-2026-0086',
                'title' => 'Non-Disclosure & Intellectual Property Assignment Undertaking',
                'category' => 'NDA / IP Agreement',
                'record_date' => '2026-07-28',
                'end_date' => null,
                'status' => 'Active',
                'status_badge_class' => 'active',
                'description' => 'Standard corporate confidentiality, proprietary code safeguards, and IP assignment deed.',
                'metadata' => [
                    'employee_name' => 'Mark Gabriel Cruz',
                    'document_type' => 'NDA / IP Agreement',
                    'title' => 'Non-Disclosure & Intellectual Property Assignment Undertaking',
                    'status' => 'Active',
                    'description' => 'Standard corporate confidentiality, proprietary code safeguards, and IP assignment deed.',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Signed_NDA_IP_Deed.pdf',
            ],

            // ATTENDANCE RECORDS
            [
                'id' => 10,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'attendance',
                'reference_no' => 'ATT-2026-0101',
                'title' => 'Maria Santos',
                'category' => 'Present',
                'record_date' => '2026-09-08',
                'end_date' => null,
                'status' => 'Present',
                'status_badge_class' => 'active',
                'description' => 'Regular corporate headquarters badge-in. Standard 9-hour on-site operational shift.',
                'metadata' => [
                    'employee_name' => 'Maria Santos',
                    'date' => '2026-09-08',
                    'attendance_status' => 'Present',
                    'time_in' => '08:30 AM',
                    'time_out' => '05:35 PM',
                    'notes' => 'Regular headquarters badge-in.',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 11,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'attendance',
                'reference_no' => 'ATT-2026-0100',
                'title' => 'Atty. Juan Carlos Reyes',
                'category' => 'Present',
                'record_date' => '2026-09-08',
                'end_date' => null,
                'status' => 'Present',
                'status_badge_class' => 'active',
                'description' => 'Hybrid on-site workstation log. Participated in afternoon legal briefing.',
                'metadata' => [
                    'employee_name' => 'Atty. Juan Carlos Reyes',
                    'date' => '2026-09-08',
                    'attendance_status' => 'Present',
                    'time_in' => '08:55 AM',
                    'time_out' => '06:10 PM',
                    'notes' => 'Hybrid on-site log.',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],
            [
                'id' => 12,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'attendance',
                'reference_no' => 'ATT-2026-0099',
                'title' => 'Roberto Jose Dizon',
                'category' => 'On Leave',
                'record_date' => '2026-09-08',
                'end_date' => null,
                'status' => 'On Leave',
                'status_badge_class' => 'review',
                'description' => 'Covered by approved 5-day vacation leave application LVE-2026-0033.',
                'metadata' => [
                    'employee_name' => 'Roberto Jose Dizon',
                    'date' => '2026-09-08',
                    'attendance_status' => 'On Leave',
                    'time_in' => null,
                    'time_out' => null,
                    'notes' => 'Approved vacation leave.',
                ],
                'attachment_path' => null,
                'attachment_name' => null,
            ],

            // LEAVE RECORDS
            [
                'id' => 13,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'leave',
                'reference_no' => 'LVE-2026-0033',
                'title' => 'Roberto Jose Dizon',
                'category' => 'Vacation Leave',
                'record_date' => '2026-09-07',
                'end_date' => '2026-09-11',
                'status' => 'Approved',
                'status_badge_class' => 'active',
                'description' => 'Annual family vacation leave. Duties endorsed to logistics backup officer.',
                'metadata' => [
                    'employee_name' => 'Roberto Jose Dizon',
                    'leave_type' => 'Vacation Leave',
                    'start_date' => '2026-09-07',
                    'end_date' => '2026-09-11',
                    'number_of_days' => 5,
                    'reason' => 'Annual family vacation. Duties temporarily endorsed to dispatch support officer.',
                    'status' => 'Approved',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Approved_Leave_Form_LVE-0033.pdf',
            ],
            [
                'id' => 14,
                'account_id' => $accountId,
                'user_id' => $userId,
                'record_type' => 'leave',
                'reference_no' => 'LVE-2026-0032',
                'title' => 'Beatrice Anne Tan',
                'category' => 'Sick Leave',
                'record_date' => '2026-09-15',
                'end_date' => '2026-09-16',
                'status' => 'Pending',
                'status_badge_class' => 'pending',
                'description' => 'Scheduled outpatient diagnostic follow-up and medical rest.',
                'metadata' => [
                    'employee_name' => 'Beatrice Anne Tan',
                    'leave_type' => 'Sick Leave',
                    'start_date' => '2026-09-15',
                    'end_date' => '2026-09-16',
                    'number_of_days' => 2,
                    'reason' => 'Scheduled outpatient diagnostic follow-up.',
                    'status' => 'Pending',
                ],
                'attachment_path' => null,
                'attachment_name' => 'Doctor_Consultation_Slip.pdf',
            ],
        ];
    }
}
